apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vegetable-app
  namespace: argocd

spec:
  project: default

  source:
    repoURL: https://sivamani0.github.io/Vegetable-app-Helm-chart
    targetRevision: main
    path: charts/veg-app

  destination:
    server: https://kubernetes.default.svc
    namespace: sivamani-ns

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
